"""empty message

Revision ID: c75ce28a1eb5
Revises: 
Create Date: 2018-12-30 22:55:56.251064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75ce28a1eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Battle_name'), 'Battle', ['name'], unique=True)
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Campaign_name'), 'Campaign', ['name'], unique=True)
    op.create_table('Enemy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('current_health', sa.Integer(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Enemy_name'), 'Enemy', ['name'], unique=True)
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Item_name'), 'Item', ['name'], unique=True)
    op.create_table('Player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('current_health', sa.Integer(), nullable=False),
    sa.Column('carry_capacity', sa.Float(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Player_name'), 'Player', ['name'], unique=True)
    op.create_table('BattleEnemy',
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['Battle.id'], ),
    sa.ForeignKeyConstraint(['enemy_id'], ['Enemy.id'], ),
    sa.PrimaryKeyConstraint('battle_id', 'enemy_id')
    )
    op.create_table('CampaignBattle',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['Battle.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'battle_id')
    )
    op.create_table('CampaignPlayer',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'player_id')
    )
    op.create_table('PlayerItem',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlayerItem')
    op.drop_table('CampaignPlayer')
    op.drop_table('CampaignBattle')
    op.drop_table('BattleEnemy')
    op.drop_index(op.f('ix_Player_name'), table_name='Player')
    op.drop_table('Player')
    op.drop_index(op.f('ix_Item_name'), table_name='Item')
    op.drop_table('Item')
    op.drop_index(op.f('ix_Enemy_name'), table_name='Enemy')
    op.drop_table('Enemy')
    op.drop_index(op.f('ix_Campaign_name'), table_name='Campaign')
    op.drop_table('Campaign')
    op.drop_index(op.f('ix_Battle_name'), table_name='Battle')
    op.drop_table('Battle')
    # ### end Alembic commands ###
